@startuml

actor Utente
participant "RUV" as RUV
participant "RUC" as RUC
participant "Server" as Server
participant "DB" as DB

Utente -> RUV : apre recensioni
RUV -> RUC : init

Utente -> RUV : seleziona recensione
Utente -> RUV : clicca Elimina
RUV -> RUC : elimina(id)

RUC -> Server : deleteRecensione(id)
Server -> DB : delete
DB --> Server : ok
Server --> RUC : ok
RUC -> RUV : aggiorna

@enduml
