package common;

public enum MessageType {
    LOGIN,
    REGISTRAZIONE,
    CERCA_RISTORANTI,
    VISUALIZZA_RISTORANTE,
    AGGIUNGI_RECENSIONE,
    MODIFICA_RECENSIONE,
    ELIMINA_RECENSIONE,
    AGGIUNGI_PREFERITO,
    RIMUOVI_PREFERITO,
    VISUALIZZA_PREFERITI,
    AGGIUNGI_RISTORANTE,
    VISUALIZZA_RIEPILOGO_GESTORE,
    VISUALIZZA_RECENSIONI_GESTORE,
    RISPONDI_RECENSIONE
}
