package common;

public enum MessageType {

    // UTENTE
    LOGIN,
    REGISTRAZIONE,

    // RISTORANTI MICHELIN (sola lettura)
    CERCA_RISTORANTI,
    VISUALIZZA_RISTORANTE,

    // RISTORANTI UTENTE (CRUD)
    AGGIUNGI_RISTORANTE,
    MODIFICA_RISTORANTE,
    ELIMINA_RISTORANTE,
    VISUALIZZA_RIEPILOGO_GESTORE,
    VISUALIZZA_RISTORANTE_UTENTE,

    // RECENSIONI (MICHELIN + UTENTE)
    AGGIUNGI_RECENSIONE,
    MODIFICA_RECENSIONE,
    ELIMINA_RECENSIONE,
    VISUALIZZA_RECENSIONI_RISTORANTE_UTENTE,
    VISUALIZZA_RECENSIONI_GESTORE,
    RISPONDI_RECENSIONE,
    VISUALIZZA_RECENSIONI_RISTORANTE,

    // PREFERITI
    AGGIUNGI_PREFERITO,
    RIMUOVI_PREFERITO,
    VISUALIZZA_PREFERITI
}
